export const localeSet = {
  en: {
    greet: 'Hi! Please type your first todo right here',
    only: 'Only',
    left: 'left',
    deleteAll: 'Delete completed tasks',
    priority: 'Priority',
    start: 'Start',
    showing: 'Now showing todos',
    of: 'of',
    all: 'All',
    active: 'Active',
    done: 'Done',
    add: 'I need to do...',
    title: 'My Awesome ToDo App by Veronika Zayarnaya',
    desc: 'the simple ToDo app',
    heading: 'My Todos',
    addtodo: 'Add to do',
    ru: 'Russian',
    en: 'English',
    markDone: 'Mark todo as completed',
    editTodo: 'Edit todo',
    arrowUp: 'Increase priority',
    arrowDown: 'Decrease priority',
    trash: 'Delete todo',
    page: 'Move to page ',
    prioritySort: 'Sort by priority',
    startSort: 'Sort by add time',
  },
  ru: {
    greet: 'Привет! Напиши свою первую задачу:',
    only: 'Осталось всего',
    left: '',
    deleteAll: 'Удалить сделанное',
    priority: 'Важность',
    start: 'Время добавления',
    showing: 'Показываем',
    of: 'из',
    all: 'Все',
    active: 'Активные',
    done: 'Сделанные',
    add: 'Мне нужно сделать...',
    title: 'Классный список задач от Вероники Заярной',
    desc: 'простая тудушница',
    heading: 'Мои тудушки',
    addtodo: 'Добавить тудушку',
    ru: 'Русский',
    en: 'Английский',
    markDone: 'Отметить как сделанное',
    editTodo: 'Редактировать тудушку',
    arrowUp: 'Повысить приоритет',
    arrowDown: 'Понизить приоритет',
    trash: 'Удалить тудушку',
    page: 'Перейти на страницу ',
    prioritySort: 'Сортировать по приоритету',
    startSort: 'Сортировать по времени добавления',
  },
};
