export const localeSet = {
  en: {
    greet: 'Hi! Please type your first todo right here',
    only: 'Only',
    left: 'left',
    deleteAll: 'Delete completed tasks',
    priority: 'Priority',
    start: 'Start',
    showing: 'Now showing todos',
    of: 'of',
    all: 'All',
    active: 'Active',
    done: 'Done',
    add: 'I need to do...',
    title: 'My Awesome ToDo App by Veronika Zayarnaya',
    desc: 'the simple ToDo app',
    heading: 'My Todos',
  },
  ru: {
    greet: 'Привет! Напиши свою первую задачу:',
    only: 'Осталось всего',
    left: '',
    deleteAll: 'Удалить сделанное',
    priority: 'Важность',
    start: 'Время добавления',
    showing: 'Показываем',
    of: 'из',
    all: 'Все',
    active: 'Активные',
    done: 'Сделанные',
    add: 'Мне нужно сделать...',
    title: 'Классный список задач от Вероники Заярной',
    desc: 'простая тудушница',
    heading: 'Мои тудушки',
  },
};
